### ISSUE TITLE
completion and pd 0.50-0 test1

### ISSUE THREAD

**Issue by sevdh** [HenriAugusto/completion-plugin#23]
The completion plugin doesn’t seem to work with pd 0.50-0 test1. When I put an object, type for example ‘sf’ and press the tab key I get  ‘… couldn’t create’ in the Pd window instead of a list of objects that include ’sf’ in their name.
I’m on macos 10.14.6 and use [completion-plugin] version 0.46.1

**Comment by HenriAugusto** [comment]
Yes. That is because the Tab key is now used by PD. (It switches objects). So we'll have to bind the plugin to other key. Probably Ctrl+Space which is familair to a lot of programmers.

I'll put a next release soon.

**Comment by sevdh** [comment]
Excellent. Completion is a really helpful plugin!

**Comment by HenriAugusto** [comment]
fixed in 0.47.0-test1
