### ISSUE TITLE
issues with pd 0.50 on macOs

### ISSUE THREAD

**Issue by megrimm** [HenriAugusto/completion-plugin#31]
Hello,

great plugin!

install from deken 0.47
seems to not be working correctly on macOS with pd 0.50.

What is the key commands? "tab" does not work. I do not seem to see documentation on a new command key other that in the changelog that says ctl+space... but that does not work either.

hmmmmm

some small things....

in pd console I get "[completion-plugin] version 0.46.1" even though it is 0.47?

under preferences->autocomplete settings the "help" button doesn't work. console says "Ignoring '/Users/megrimm/Documents/Pd/externals/ofelia/README.pd': doesn't exist" which is weird...

maybe there is a way to change the shortcut keys? but i do not see option?

also the readme.deken.pd still lists version as 0.46.0

hmmmm ... unless its all a fault on my end somehow :)

**Comment by megrimm** [comment]
i jumped the gun on this... seems installing from deken didn't overwrite 0.46. i had to manually delete and reinstall. Ctrl+space DOES work now....

**Comment by HenriAugusto** [comment]
> under preferences->autocomplete settings the "help" button doesn't work. console says "Ignoring '/Users/megrimm/Documents/Pd/externals/ofelia/README.pd': doesn't exist" which is weird...

Seems like issue #30 which was just fixed :)

> i jumped the gun on this... seems installing from deken didn't overwrite 0.46. i had to manually delete and reinstall. Ctrl+space DOES work now....

hahah okay! :)

I'm about to create an issue about the shortcut on OS X. You might be interested in issue #32
