### ISSUE TITLE
mousewheel

### ISSUE THREAD

**Issue by mxa** [HenriAugusto/completion-plugin#7]
I wish the mousewheel would work to scroll in the tab selection box.

**Comment by HenriAugusto** [comment]
What OS are you using?

Nothing happens when you mouse scrool? Here it scrolls the list without changing the selection.

**Comment by HenriAugusto** [comment]
Indeed! Thanks for pointing that out. This will be fixed in the next release.

Scrolling with the mouse wheel was calling `choose_selected`. Fixed by checking 

`%b eq 1`

 inside the

`<ButtonRelease>`

event
